base_model: meetkai/functionary-medium-v2.2
model_type: MixtralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: false

load_in_8bit: false
load_in_4bit: true
strict: false

model_config:
  output_router_logits: true

datasets:
  - path: milsunone/cural-functionary-medium-5100

dataset_prepared_path:
val_set_size: 0.005
output_dir: cural-functionary-medium-v2.2
resume_from_checkpoint:
hf_use_auth_token:

adapter:  qlora
lora_model_dir:

sequence_len: 5100
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

wandb_project: cural-functionary-medium-v2.2
wandb_entity: 
wandb_watch:
wandb_run_id: 
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 3
num_epochs: 10
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs:
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.01
save_steps: 0.01
save_total_limit: 2
eval_sample_packing: true
debug:
deepspeed: deepspeed/zero2.json
weight_decay: 0.05
fsdp:
fsdp_config:
trust_remote_code: true